name: Validate data

permissions: {}

on:
  push:
    paths:
      - "data/mods/**"
      - "public/images/**"
      - "data/tags.json"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate Files
        run: bash scripts/validate-data.sh
